// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onuwzchgogqtxegudysk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9udXd6Y2hnb2dxdHhlZ3VkeXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MTg2NDksImV4cCI6MjA4OTA5NDY0OX0.7CKM5hU4AOV1wJWnhyPRMt4ym8x5EIRJEv1_ov7CRHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});